title: "India.gg"
description: "Your daily dose of Indian games, gamers, and gaming news"
theme: jekyll-theme-mediumish
url: "https://india.gg"
baseurl: ""

author:
  name: "Subhash"
#  email: "your-email@example.com"

# Social links
social:
  twitter: your_twitter_handle
  github: your_github_handle

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
