title: "India.gg"
description: "Your daily dose of Indian games and its news"
theme: minima

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.india.gg" # the base hostname & protocol for your site

# Author settings
author:
  name: "Subhash"
  email: "subhashdasyam@users.noreply.github.com"

# Markdown settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Minima theme settings
minima:
  social_links:
    twitter: soon
    github: soon
    # Add more social links as needed

# Default settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: post
    values:
      layout: "post"
      tags: Other

# Build settings
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
titles_from_headings:
  strip_title: true
  collections: true


